export const FETCH_DATA_REQUEST = "FETCH_MOVIE_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_MOVIE_FAILURE";

export const FETCH_DETAILS_REQUEST = "FETCH_DETAILS_REQUEST";
export const FETCH_DETAILS_SUCCESS = "FETCH_DETAILS_SUCCESS";
export const FETCH_DETAILS_ERROR = "FETCH_DETAILS_ERROR";

export const FETCH_BOOKMARK_REQUEST = "FETCH_BOOKMARK_REQUEST";
export const FETCH_BOOKMARK_SUCCESS = "FETCH_BOOKMARK_SUCCESS";
export const FETCH_BOOKMARK_FAILURE = "FETCH_BOOKMARK_FAILURE";

export const ADD_BOOKMARK_REQUEST = "ADD_BOOKMARK_REQUEST";
export const ADD_BOOKMARK_SUCCESS = "ADD_BOOKMARK_SUCCESS";
export const ADD_BOOKMARK_FAILURE = "ADD_BOOKMARK_FAILURE";

export const DELETE_BOOKMARK_REQUEST = "DELETE_BOOKMARK_REQUEST";
export const DELETE_BOOKMARK_SUCCESS = "DELETE_BOOKMARK_SUCCESS";
export const DELETE_BOOKMARK_FAILURE = "DELETE_BOOKMARK_FAILURE";
