export const FETCH_DATA_REQUEST = "FETCH_MOVIE_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_MOVIE_FAILURE";

export const FETCH_DETAILS_REQUEST = "FETCH_DETAILS_REQUEST";
export const FETCH_DETAILS_SUCCESS = "FETCH_DETAILS_SUCCESS";
export const FETCH_DETAILS_ERROR = "FETCH_DETAILS_ERROR";

export const FETCH_BOOKMARK_REQUEST = "FETCH_BOOKMARK_REQUEST";
export const FETCH_BOOKMARK_SUCCESS = "FETCH_BOOKMARK_SUCCESS";
export const FETCH_BOOKMARK_FAILURE = "FETCH_BOOKMARK_FAILURE";
